apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: roxctl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: roxctl
    app.kubernetes.io/part-of: devfile-sample
  name: roxctlxmnj
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: roxctl
    weight: 100
status: {}
